
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

CREATE EXTENSION IF NOT EXISTS "http" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE OR REPLACE FUNCTION "public"."check_view_granted"("parameter_token_address" "text") RETURNS boolean
    LANGUAGE "plpgsql"
    AS $$begin return auth.role() = 'authenticated'::text
and (
   (
      (
         SELECT pal_tokens.owner
         FROM pal_tokens
         WHERE (pal_tokens.token_address = parameter_token_address)
      ) = (
         SELECT user_details.wallet_address
         FROM user_details
         WHERE (user_details.id = auth.uid())
      )
   )
   or (
      (
         SELECT pal_tokens.view_token_required
         FROM pal_tokens
         WHERE (pal_tokens.token_address = parameter_token_address)
      ) <= (
         SELECT pal_token_balances.last_fetched_balance
         FROM pal_token_balances
         WHERE (
               (pal_token_balances.token_address = parameter_token_address)
               AND (
                  pal_token_balances.wallet_address = (
                     SELECT user_details.wallet_address
                     FROM user_details
                     WHERE (user_details.id = auth.uid())
                  )
               )
            )
      )
   )
);
end;$$;

ALTER FUNCTION "public"."check_view_granted"("parameter_token_address" "text") OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."increment_trading_fees_earned"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$begin
  IF new.event_type = 1 THEN
    update pal_tokens
    set
      trading_fees_earned = trading_fees_earned + new.args[7]::numeric
    where
      token_address = new.args[2];
  END IF;
  return null;
end;$$;

ALTER FUNCTION "public"."increment_trading_fees_earned"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."new_pal_token"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$begin
  IF new.event_type = 0 THEN
    insert into pal_tokens (token_address, owner, name, symbol) values (
      new.args[2], new.args[1], new.args[3], new.args[4]
    ) ON CONFLICT (token_address)
    DO NOTHING;
  END IF;
  return null;
end;$$;

ALTER FUNCTION "public"."new_pal_token"() OWNER TO "postgres";

CREATE OR REPLACE FUNCTION "public"."update_last_message_sent_at"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$begin
  update pal_tokens
  set
    last_message_sent_at = now()
  where
    token_address = new.token_address;
  return null;
end;$$;

ALTER FUNCTION "public"."update_last_message_sent_at"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."token_chat_messages" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "token_address" "text" NOT NULL,
    "author" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "message_type" smallint NOT NULL,
    "message" "text",
    "rich" "jsonb",
    "translated" "jsonb",
    "author_name" "text",
    "author_avatar_url" "text"
);

ALTER TABLE "public"."token_chat_messages" OWNER TO "postgres";

ALTER TABLE "public"."token_chat_messages" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."chat_messages_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."nonce" (
    "id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "nonce" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "wallet_address" "text" NOT NULL
);

ALTER TABLE "public"."nonce" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."pal_contract_events" (
    "block_number" bigint NOT NULL,
    "log_index" bigint NOT NULL,
    "event_type" smallint NOT NULL,
    "args" "text"[] DEFAULT '{}'::"text"[] NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "wallet_address" "text" NOT NULL,
    "token_address" "text" NOT NULL
);

ALTER TABLE "public"."pal_contract_events" OWNER TO "postgres";

ALTER TABLE "public"."pal_contract_events" ALTER COLUMN "block_number" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."pal_contract_events_block_number_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."pal_token_balances" (
    "token_address" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "wallet_address" "text" NOT NULL,
    "last_fetched_balance" numeric DEFAULT '0'::numeric NOT NULL
);

ALTER TABLE "public"."pal_token_balances" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."pal_tokens" (
    "token_address" "text" NOT NULL,
    "owner" "text" NOT NULL,
    "name" "text" NOT NULL,
    "symbol" "text" NOT NULL,
    "metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "view_token_required" numeric DEFAULT '1000000000000000000'::numeric NOT NULL,
    "write_token_required" numeric DEFAULT '1000000000000000000'::numeric NOT NULL,
    "last_fetched_price" numeric DEFAULT '0'::numeric NOT NULL,
    "last_message_sent_at" timestamp with time zone,
    "hiding" boolean DEFAULT false NOT NULL,
    "trading_fees_earned" numeric DEFAULT '0'::numeric NOT NULL
);

ALTER TABLE "public"."pal_tokens" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."tracked_event_blocks" (
    "id" bigint NOT NULL,
    "block_number" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone
);

ALTER TABLE "public"."tracked_event_blocks" OWNER TO "postgres";

ALTER TABLE "public"."tracked_event_blocks" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tracked_event_blocks_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."user_details" (
    "id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "wallet_address" "text",
    "metadata" "jsonb" DEFAULT '{}'::"jsonb" NOT NULL,
    "profile_image" "text",
    "display_name" "text"
);

ALTER TABLE "public"."user_details" OWNER TO "postgres";

ALTER TABLE ONLY "public"."token_chat_messages"
    ADD CONSTRAINT "chat_messages_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."nonce"
    ADD CONSTRAINT "nonce_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."pal_contract_events"
    ADD CONSTRAINT "pal_contract_events_pkey" PRIMARY KEY ("block_number", "log_index");

ALTER TABLE ONLY "public"."pal_token_balances"
    ADD CONSTRAINT "pal_token_balances_pkey" PRIMARY KEY ("token_address", "wallet_address");

ALTER TABLE ONLY "public"."pal_tokens"
    ADD CONSTRAINT "pal_tokens_pkey" PRIMARY KEY ("token_address");

ALTER TABLE ONLY "public"."tracked_event_blocks"
    ADD CONSTRAINT "tracked_event_blocks_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_details"
    ADD CONSTRAINT "user_wallets_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_details"
    ADD CONSTRAINT "user_wallets_wallet_address_key" UNIQUE ("wallet_address");

CREATE TRIGGER "increment_trading_fees_earned" AFTER INSERT ON "public"."pal_contract_events" FOR EACH ROW EXECUTE FUNCTION "public"."increment_trading_fees_earned"();

CREATE TRIGGER "new_pal_token" AFTER INSERT ON "public"."pal_contract_events" FOR EACH ROW EXECUTE FUNCTION "public"."new_pal_token"();

CREATE TRIGGER "update_last_message_sent_at" AFTER INSERT ON "public"."token_chat_messages" FOR EACH ROW EXECUTE FUNCTION "public"."update_last_message_sent_at"();

ALTER TABLE ONLY "public"."token_chat_messages"
    ADD CONSTRAINT "token_chat_messages_author_fkey" FOREIGN KEY ("author") REFERENCES "auth"."users"("id");

ALTER TABLE ONLY "public"."user_details"
    ADD CONSTRAINT "user_details_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");

CREATE POLICY "allow anon select" ON "public"."pal_contract_events" FOR SELECT USING (true);

CREATE POLICY "allow anon select" ON "public"."pal_token_balances" FOR SELECT USING (true);

CREATE POLICY "allow anon select" ON "public"."pal_tokens" FOR SELECT USING (true);

CREATE POLICY "allow anon select" ON "public"."user_details" FOR SELECT USING (true);

ALTER TABLE "public"."nonce" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."pal_contract_events" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."pal_token_balances" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."pal_tokens" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."token_chat_messages" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tracked_event_blocks" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "update pal token's metadata" ON "public"."pal_tokens" FOR UPDATE USING (("owner" = ( SELECT "user_details"."wallet_address"
   FROM "public"."user_details"
  WHERE ("user_details"."id" = "auth"."uid"())))) WITH CHECK (("owner" = ( SELECT "user_details"."wallet_address"
   FROM "public"."user_details"
  WHERE ("user_details"."id" = "auth"."uid"()))));

ALTER TABLE "public"."user_details" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "view only holder or owner" ON "public"."token_chat_messages" FOR SELECT TO "authenticated" USING (((( SELECT "pal_tokens"."owner"
   FROM "public"."pal_tokens"
  WHERE ("pal_tokens"."token_address" = "token_chat_messages"."token_address")) = ( SELECT "user_details"."wallet_address"
   FROM "public"."user_details"
  WHERE ("user_details"."id" = "auth"."uid"()))) OR (( SELECT "pal_tokens"."view_token_required"
   FROM "public"."pal_tokens"
  WHERE ("pal_tokens"."token_address" = "token_chat_messages"."token_address")) <= ( SELECT "pal_token_balances"."last_fetched_balance"
   FROM "public"."pal_token_balances"
  WHERE (("pal_token_balances"."token_address" = "token_chat_messages"."token_address") AND ("pal_token_balances"."wallet_address" = ( SELECT "user_details"."wallet_address"
           FROM "public"."user_details"
          WHERE ("user_details"."id" = "auth"."uid"()))))))));

CREATE POLICY "write only holder or owner" ON "public"."token_chat_messages" FOR INSERT TO "authenticated" WITH CHECK ((("auth"."uid"() = "author") AND ((( SELECT "pal_tokens"."owner"
   FROM "public"."pal_tokens"
  WHERE ("pal_tokens"."token_address" = "token_chat_messages"."token_address")) = ( SELECT "user_details"."wallet_address"
   FROM "public"."user_details"
  WHERE ("user_details"."id" = "auth"."uid"()))) OR (( SELECT "pal_tokens"."write_token_required"
   FROM "public"."pal_tokens"
  WHERE ("pal_tokens"."token_address" = "token_chat_messages"."token_address")) <= ( SELECT "pal_token_balances"."last_fetched_balance"
   FROM "public"."pal_token_balances"
  WHERE (("pal_token_balances"."token_address" = "token_chat_messages"."token_address") AND ("pal_token_balances"."wallet_address" = ( SELECT "user_details"."wallet_address"
           FROM "public"."user_details"
          WHERE ("user_details"."id" = "auth"."uid"())))))))));

REVOKE USAGE ON SCHEMA "public" FROM PUBLIC;
GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON FUNCTION "public"."check_view_granted"("parameter_token_address" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."check_view_granted"("parameter_token_address" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."check_view_granted"("parameter_token_address" "text") TO "service_role";

GRANT ALL ON FUNCTION "public"."increment_trading_fees_earned"() TO "anon";
GRANT ALL ON FUNCTION "public"."increment_trading_fees_earned"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."increment_trading_fees_earned"() TO "service_role";

GRANT ALL ON FUNCTION "public"."new_pal_token"() TO "anon";
GRANT ALL ON FUNCTION "public"."new_pal_token"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."new_pal_token"() TO "service_role";

GRANT ALL ON FUNCTION "public"."update_last_message_sent_at"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_last_message_sent_at"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_last_message_sent_at"() TO "service_role";

GRANT ALL ON TABLE "public"."token_chat_messages" TO "anon";
GRANT ALL ON TABLE "public"."token_chat_messages" TO "authenticated";
GRANT ALL ON TABLE "public"."token_chat_messages" TO "service_role";

GRANT ALL ON SEQUENCE "public"."chat_messages_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."chat_messages_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."chat_messages_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."nonce" TO "anon";
GRANT ALL ON TABLE "public"."nonce" TO "authenticated";
GRANT ALL ON TABLE "public"."nonce" TO "service_role";

GRANT ALL ON TABLE "public"."pal_contract_events" TO "anon";
GRANT ALL ON TABLE "public"."pal_contract_events" TO "authenticated";
GRANT ALL ON TABLE "public"."pal_contract_events" TO "service_role";

GRANT ALL ON SEQUENCE "public"."pal_contract_events_block_number_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."pal_contract_events_block_number_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."pal_contract_events_block_number_seq" TO "service_role";

GRANT ALL ON TABLE "public"."pal_token_balances" TO "anon";
GRANT ALL ON TABLE "public"."pal_token_balances" TO "authenticated";
GRANT ALL ON TABLE "public"."pal_token_balances" TO "service_role";

GRANT ALL ON TABLE "public"."pal_tokens" TO "anon";
GRANT ALL ON TABLE "public"."pal_tokens" TO "authenticated";
GRANT ALL ON TABLE "public"."pal_tokens" TO "service_role";

GRANT ALL ON TABLE "public"."tracked_event_blocks" TO "anon";
GRANT ALL ON TABLE "public"."tracked_event_blocks" TO "authenticated";
GRANT ALL ON TABLE "public"."tracked_event_blocks" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tracked_event_blocks_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tracked_event_blocks_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tracked_event_blocks_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."user_details" TO "anon";
GRANT ALL ON TABLE "public"."user_details" TO "authenticated";
GRANT ALL ON TABLE "public"."user_details" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
