/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common.js";

export interface PalInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyToken"
      | "calculateAdditionalTokenOwnerFee"
      | "createToken"
      | "getBuyPrice"
      | "getBuyPriceAfterFee"
      | "getPrice"
      | "getSellPrice"
      | "getSellPriceAfterFee"
      | "initialize"
      | "isPalUserToken"
      | "membershipToken"
      | "membershipWeight"
      | "owner"
      | "protocolFeeDestination"
      | "protocolFeePercent"
      | "renounceOwnership"
      | "sellToken"
      | "setMembershipToken"
      | "setMembershipWeight"
      | "setProtocolFeeDestination"
      | "setProtocolFeePercent"
      | "setTokenOwnerFeePercent"
      | "tokenOwnerFeePercent"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Initialized"
      | "OwnershipTransferred"
      | "SetMembershipToken"
      | "SetMembershipWeight"
      | "SetProtocolFeeDestination"
      | "SetProtocolFeePercent"
      | "SetTokenOwnerFeePercent"
      | "Trade"
      | "UserTokenCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateAdditionalTokenOwnerFee",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createToken",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyPrice",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyPriceAfterFee",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellPrice",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellPriceAfterFee",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPalUserToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "membershipToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "membershipWeight",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolFeeDestination",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sellToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMembershipToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMembershipWeight",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFeeDestination",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFeePercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenOwnerFeePercent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOwnerFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "buyToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateAdditionalTokenOwnerFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyPriceAfterFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSellPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellPriceAfterFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isPalUserToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "membershipToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "membershipWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeDestination",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sellToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMembershipToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMembershipWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFeeDestination",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenOwnerFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOwnerFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetMembershipTokenEvent {
  export type InputTuple = [token: AddressLike];
  export type OutputTuple = [token: string];
  export interface OutputObject {
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetMembershipWeightEvent {
  export type InputTuple = [weight: BigNumberish];
  export type OutputTuple = [weight: bigint];
  export interface OutputObject {
    weight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetProtocolFeeDestinationEvent {
  export type InputTuple = [destination: AddressLike];
  export type OutputTuple = [destination: string];
  export interface OutputObject {
    destination: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetProtocolFeePercentEvent {
  export type InputTuple = [percent: BigNumberish];
  export type OutputTuple = [percent: bigint];
  export interface OutputObject {
    percent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetTokenOwnerFeePercentEvent {
  export type InputTuple = [percent: BigNumberish];
  export type OutputTuple = [percent: bigint];
  export interface OutputObject {
    percent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TradeEvent {
  export type InputTuple = [
    trader: AddressLike,
    tokenAddress: AddressLike,
    isBuy: boolean,
    amount: BigNumberish,
    price: BigNumberish,
    protocolFee: BigNumberish,
    tokenOwnerFee: BigNumberish,
    supply: BigNumberish
  ];
  export type OutputTuple = [
    trader: string,
    tokenAddress: string,
    isBuy: boolean,
    amount: bigint,
    price: bigint,
    protocolFee: bigint,
    tokenOwnerFee: bigint,
    supply: bigint
  ];
  export interface OutputObject {
    trader: string;
    tokenAddress: string;
    isBuy: boolean;
    amount: bigint;
    price: bigint;
    protocolFee: bigint;
    tokenOwnerFee: bigint;
    supply: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserTokenCreatedEvent {
  export type InputTuple = [
    owner: AddressLike,
    tokenAddress: AddressLike,
    name: string,
    symbol: string
  ];
  export type OutputTuple = [
    owner: string,
    tokenAddress: string,
    name: string,
    symbol: string
  ];
  export interface OutputObject {
    owner: string;
    tokenAddress: string;
    name: string;
    symbol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Pal extends BaseContract {
  connect(runner?: ContractRunner | null): Pal;
  waitForDeployment(): Promise<this>;

  interface: PalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyToken: TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;

  calculateAdditionalTokenOwnerFee: TypedContractMethod<
    [price: BigNumberish, tokenOwner: AddressLike],
    [bigint],
    "view"
  >;

  createToken: TypedContractMethod<
    [name: string, symbol: string],
    [string],
    "nonpayable"
  >;

  getBuyPrice: TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;

  getBuyPriceAfterFee: TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;

  getPrice: TypedContractMethod<
    [supply: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;

  getSellPrice: TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;

  getSellPriceAfterFee: TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _protocolFeeDestination: AddressLike,
      _protocolFeePercent: BigNumberish,
      _tokenOwnerFeePercent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  isPalUserToken: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  membershipToken: TypedContractMethod<[], [string], "view">;

  membershipWeight: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  protocolFeeDestination: TypedContractMethod<[], [string], "view">;

  protocolFeePercent: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sellToken: TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMembershipToken: TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  setMembershipWeight: TypedContractMethod<
    [_weight: BigNumberish],
    [void],
    "nonpayable"
  >;

  setProtocolFeeDestination: TypedContractMethod<
    [_feeDestination: AddressLike],
    [void],
    "nonpayable"
  >;

  setProtocolFeePercent: TypedContractMethod<
    [_feePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTokenOwnerFeePercent: TypedContractMethod<
    [_feePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenOwnerFeePercent: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyToken"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "calculateAdditionalTokenOwnerFee"
  ): TypedContractMethod<
    [price: BigNumberish, tokenOwner: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createToken"
  ): TypedContractMethod<
    [name: string, symbol: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBuyPrice"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBuyPriceAfterFee"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<
    [supply: BigNumberish, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSellPrice"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSellPriceAfterFee"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _protocolFeeDestination: AddressLike,
      _protocolFeePercent: BigNumberish,
      _tokenOwnerFeePercent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isPalUserToken"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "membershipToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "membershipWeight"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolFeeDestination"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "protocolFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sellToken"
  ): TypedContractMethod<
    [tokenAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMembershipToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMembershipWeight"
  ): TypedContractMethod<[_weight: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProtocolFeeDestination"
  ): TypedContractMethod<[_feeDestination: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProtocolFeePercent"
  ): TypedContractMethod<[_feePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTokenOwnerFeePercent"
  ): TypedContractMethod<[_feePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokenOwnerFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SetMembershipToken"
  ): TypedContractEvent<
    SetMembershipTokenEvent.InputTuple,
    SetMembershipTokenEvent.OutputTuple,
    SetMembershipTokenEvent.OutputObject
  >;
  getEvent(
    key: "SetMembershipWeight"
  ): TypedContractEvent<
    SetMembershipWeightEvent.InputTuple,
    SetMembershipWeightEvent.OutputTuple,
    SetMembershipWeightEvent.OutputObject
  >;
  getEvent(
    key: "SetProtocolFeeDestination"
  ): TypedContractEvent<
    SetProtocolFeeDestinationEvent.InputTuple,
    SetProtocolFeeDestinationEvent.OutputTuple,
    SetProtocolFeeDestinationEvent.OutputObject
  >;
  getEvent(
    key: "SetProtocolFeePercent"
  ): TypedContractEvent<
    SetProtocolFeePercentEvent.InputTuple,
    SetProtocolFeePercentEvent.OutputTuple,
    SetProtocolFeePercentEvent.OutputObject
  >;
  getEvent(
    key: "SetTokenOwnerFeePercent"
  ): TypedContractEvent<
    SetTokenOwnerFeePercentEvent.InputTuple,
    SetTokenOwnerFeePercentEvent.OutputTuple,
    SetTokenOwnerFeePercentEvent.OutputObject
  >;
  getEvent(
    key: "Trade"
  ): TypedContractEvent<
    TradeEvent.InputTuple,
    TradeEvent.OutputTuple,
    TradeEvent.OutputObject
  >;
  getEvent(
    key: "UserTokenCreated"
  ): TypedContractEvent<
    UserTokenCreatedEvent.InputTuple,
    UserTokenCreatedEvent.OutputTuple,
    UserTokenCreatedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SetMembershipToken(address)": TypedContractEvent<
      SetMembershipTokenEvent.InputTuple,
      SetMembershipTokenEvent.OutputTuple,
      SetMembershipTokenEvent.OutputObject
    >;
    SetMembershipToken: TypedContractEvent<
      SetMembershipTokenEvent.InputTuple,
      SetMembershipTokenEvent.OutputTuple,
      SetMembershipTokenEvent.OutputObject
    >;

    "SetMembershipWeight(uint256)": TypedContractEvent<
      SetMembershipWeightEvent.InputTuple,
      SetMembershipWeightEvent.OutputTuple,
      SetMembershipWeightEvent.OutputObject
    >;
    SetMembershipWeight: TypedContractEvent<
      SetMembershipWeightEvent.InputTuple,
      SetMembershipWeightEvent.OutputTuple,
      SetMembershipWeightEvent.OutputObject
    >;

    "SetProtocolFeeDestination(address)": TypedContractEvent<
      SetProtocolFeeDestinationEvent.InputTuple,
      SetProtocolFeeDestinationEvent.OutputTuple,
      SetProtocolFeeDestinationEvent.OutputObject
    >;
    SetProtocolFeeDestination: TypedContractEvent<
      SetProtocolFeeDestinationEvent.InputTuple,
      SetProtocolFeeDestinationEvent.OutputTuple,
      SetProtocolFeeDestinationEvent.OutputObject
    >;

    "SetProtocolFeePercent(uint256)": TypedContractEvent<
      SetProtocolFeePercentEvent.InputTuple,
      SetProtocolFeePercentEvent.OutputTuple,
      SetProtocolFeePercentEvent.OutputObject
    >;
    SetProtocolFeePercent: TypedContractEvent<
      SetProtocolFeePercentEvent.InputTuple,
      SetProtocolFeePercentEvent.OutputTuple,
      SetProtocolFeePercentEvent.OutputObject
    >;

    "SetTokenOwnerFeePercent(uint256)": TypedContractEvent<
      SetTokenOwnerFeePercentEvent.InputTuple,
      SetTokenOwnerFeePercentEvent.OutputTuple,
      SetTokenOwnerFeePercentEvent.OutputObject
    >;
    SetTokenOwnerFeePercent: TypedContractEvent<
      SetTokenOwnerFeePercentEvent.InputTuple,
      SetTokenOwnerFeePercentEvent.OutputTuple,
      SetTokenOwnerFeePercentEvent.OutputObject
    >;

    "Trade(address,address,bool,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;
    Trade: TypedContractEvent<
      TradeEvent.InputTuple,
      TradeEvent.OutputTuple,
      TradeEvent.OutputObject
    >;

    "UserTokenCreated(address,address,string,string)": TypedContractEvent<
      UserTokenCreatedEvent.InputTuple,
      UserTokenCreatedEvent.OutputTuple,
      UserTokenCreatedEvent.OutputObject
    >;
    UserTokenCreated: TypedContractEvent<
      UserTokenCreatedEvent.InputTuple,
      UserTokenCreatedEvent.OutputTuple,
      UserTokenCreatedEvent.OutputObject
    >;
  };
}
