/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "https://esm.sh/ethers@6.7.0";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common.ts";

export interface PalTokenPriceAggregatorInterface extends Interface {
  getFunction(nameOrSignature: "getBulkTokenPrices" | "pal"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getBulkTokenPrices",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(functionFragment: "pal", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "getBulkTokenPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pal", data: BytesLike): Result;
}

export interface PalTokenPriceAggregator extends BaseContract {
  connect(runner?: ContractRunner | null): PalTokenPriceAggregator;
  waitForDeployment(): Promise<this>;

  interface: PalTokenPriceAggregatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getBulkTokenPrices: TypedContractMethod<
    [_tokens: AddressLike[]],
    [bigint[]],
    "view"
  >;

  pal: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getBulkTokenPrices"
  ): TypedContractMethod<[_tokens: AddressLike[]], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "pal"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
