/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "https://esm.sh/ethers@6.7.0";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common.ts";

export interface TokenHoldingsAggregatorInterface extends Interface {
  getFunction(
    nameOrSignature: "getERC20BalanceList_OneHolder"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getERC20BalanceList_OneHolder",
    values: [AddressLike, AddressLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getERC20BalanceList_OneHolder",
    data: BytesLike
  ): Result;
}

export interface TokenHoldingsAggregator extends BaseContract {
  connect(runner?: ContractRunner | null): TokenHoldingsAggregator;
  waitForDeployment(): Promise<this>;

  interface: TokenHoldingsAggregatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getERC20BalanceList_OneHolder: TypedContractMethod<
    [holder: AddressLike, arg1: AddressLike[]],
    [bigint[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getERC20BalanceList_OneHolder"
  ): TypedContractMethod<
    [holder: AddressLike, arg1: AddressLike[]],
    [bigint[]],
    "view"
  >;

  filters: {};
}
